gpt2:
  model_name: gpt2-small
  tokenizer_name: gpt2
  data: interpretability/ravel_analysis/data/gpt2_prompt_data.pkl
  # model: jvelja/pythia-finetune-gpt2-clusters-4-NoBSGC-lr_0.0001-Modularity-RAVEL_MIXEDFixCluster # attains low modularity score
  model: jvelja/pythia-finetune-gpt2-clusters-4-NoBSGC-lr_0.0005-Modularity-RAVEL_MIXEDFixCluster
  # nmodel: interpretability/data/models/wiki_non_modular_mlp_in_out.pt
  nmodel: jvelja/pythia-finetune-gpt2-NoBSGC-lr_0.0005-NoModularity-RAVEL_MIXEDFixCluster
  log_file: interpretability/logs/gpt2_model_analysis_on_ravel.log
  plot_path: interpretability/ravel_analysis/plots/gpt2
  data_path: interpretability/ravel_analysis/data/gpt2_prompt_data.pkl


#TODO: please change the path of the non-modular models for pythia. 

pythia70m:
  model_name: EleutherAI/pythia-70m
  tokenizer_name: EleutherAI/pythia-70m
  data: interpretability/ravel_analysis/data/pythia-70m_prompt_data.pkl
  model: jvelja/pythia-finetune-pythia-70m-clusters-4-NoBSGC-lr_5e-05-Modularity-RAVEL_MIXEDFixCluster
  nmodel: jvelja/pythia-finetune-pythia-70m-NoBSGC-lr_5e-05-NoModularity-RAVEL_MIXEDFixCluster
  log_file: interpretability/logs/pythia70m_model_analysis_on_ravel.log
  plot_path: interpretability/ravel_analysis/plots/pythia70m
  data_path: interpretability/ravel_analysis/data/pythia-70m_prompt_data


# pythia1.4b:
#   model_name: EleutherAI/pythia-1.4B
#   tokenizer_name: EleutherAI/pythia-1.4B
#   data: interpretability/ravel_analysis/data/pythia-1.4b_prompt_data.pkl
#   model: jvelja/pythia-finetune-pythia-1.4b-clusters-4-NoBSGC
#   # non_modular_model_path: interpretability/data/models/ravel_non_modular_mlp_in_out.pt
#   log_file: interpretability/logs/pythia1.4b_model_analysis_on_ravel.log
#   plot_path: interpretability/ravel_analysis/plots/pythia1.4b
#   data_path: interpretability/ravel_analysis/data/pythia1.4b