wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.11
    cli_version: 0.17.9
    framework: huggingface
    huggingface_version: 4.48.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1738015026
    t:
      1:
      - 1
      - 5
      - 11
      - 12
      - 41
      - 49
      - 51
      - 53
      - 55
      - 71
      2:
      - 1
      - 5
      - 11
      - 12
      - 41
      - 49
      - 51
      - 53
      - 55
      - 71
      3:
      - 23
      - 61
      4: 3.11.11
      5: 0.17.9
      6: 4.48.1
      8:
      - 5
      13: linux-x86_64
model_name:
  desc: null
  value: EleutherAI/pythia-70m
batch_size:
  desc: null
  value: 32
num_clusters:
  desc: null
  value: 4
steps_to_cluster:
  desc: null
  value: 150
